pow-auth/pow_assent

README.md, config/test.exs, lib/pow_assent/ecto/schema.ex, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/phoenix/views/view_helpers.ex, test/pow_assent/ecto/schema_test.exs, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/views/view_helpers_test.exs, test/support/extensions/invitation/phoenix/endpoint.ex, test/support/extensions/invitation/repo_mock.ex, test/support/extensions/invitation/user.ex, test/support/extensions/invitation/user_identity.ex, test/test_helper.exs
Resolves #36 
When using `oauth_provider_links/1` an `invitation_token` query param will be put in the URL. The controller will detect `invitation_token` query param, and load the user by the token. The changeset will automatically update `:invitation_accepted_at` if it exists.
=> Pow invitation

CHANGELOG.md, lib/pow_assent/ecto/schema.ex, test/pow_assent/ecto/schema_test.exs, test/support/extensions/email_confirmation/user.ex
Resolves #44 and #49.
The issue was that PowAssent relied on the PowEmailConfirmation changeset. Since PowEmailConfirmation will use the existing email from the user struct rather than what's set in the changeset, PowAssent will always get a nil value for email.
=> Fix e-mail confirmation bug

lib/pow_assent/strategies/oauth/base.ex
`PowAssent.Strategy.OAuth` is using `access_token_url` and `request_token_url` instead of `token_url`.
=> Fix default_config example in moduledoc

CHANGELOG.md, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/plug.ex, lib/pow_assent/strategies/oauth2.ex, lib/pow_assent/strategies/oauth2/base.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/plug_test.exs, test/pow_assent/strategies/oauth2_test.exs, test/support/strategies/oauth2_test_case.ex
From #55, this changes the flow so strategy just outputs a map with `:session_params` that will be stored in the session rather than `state`.
cc @DiodonHystrix
=> Use `session_params` in favor of `state`

CHANGELOG.md, lib/pow_assent/strategies/oauth.ex, test/pow_assent/plug_test.exs, test/pow_assent/strategies/oauth_test.exs, test/pow_assent/strategies/twitter_test.exs, test/support/strategies/oauth_test_case.ex
In OAuth `oauth_token_secret` has to be passed to get an access token.
It works with Twitter, because Twitter doesn't follow spec. At least, that's the information I found.
I will try to wrap it up tomorrow. (I need to add more tests.)
=> Fix OAuth flow

CHANGELOG.md, README.md, lib/pow_assent/phoenix/views/view_helpers.ex
Resolves #64 
Now the authorization links are explicit so you call either `authorization_link/2` or `deauthorization_link/2` to link or remove a provider authorization. The docs has been improved to explain how they work.
=> Refactor provider links

CHANGELOG.md, lib/pow_assent/ecto/user_identities/context.ex, lib/pow_assent/strategies/basecamp.ex, lib/pow_assent/strategies/github.ex, lib/pow_assent/strategies/twitter.ex, test/pow_assent/ecto/user_identities/context_test.exs, test/pow_assent/strategies/basecamp_test.exs, test/pow_assent/strategies/github_test.exs, test/pow_assent/strategies/twitter_test.exs
Now context methods will convert integer `uid` values, leaving less up to the strategy's normalize method. It didn't really make sense to have a hard requirement for binary value, since many services uses integer value for their user id.
=> Handle integer `uid` values

CHANGELOG.md, lib/pow_assent/plug.ex, test/pow_assent/plug_test.exs
With https://github.com/danschultzer/pow/pull/207 PowAssent should now use `Pow.Plug.get_plug/1`. This is a draft until Pow `1.0.9` has been released
=> Use `Pow.Plug.get_plug/1`

CHANGELOG.md, README.md, lib/pow_assent/phoenix/router.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/support/phoenix/router.ex, test/support/phoenix/views.ex
Resolves #100 
Since CSRF would be triggered this also adds docs on how to skip CSRF protection just for the POST callback route.
=> Add support for POST callback for provider

CHANGELOG.md, lib/pow_assent/config.ex, lib/pow_assent/plug.ex, test/pow_assent/config_test.exs
This prevents `String.to_atom/1` calls, and instead relies on `String.to_existing_atom/1` or use binary match instead to prevent generating new atoms.
=> Prevent `String.to_atom/1` calls

CHANGELOG.md, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/phoenix/views/view_helpers.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/views/view_helpers_test.exs, test/support/phoenix/routes.ex
Resolves #109 
This adds support for request path. In session new template, when the `PowAssent.ViewHelpers.provider_links/1` or `PowAssent.ViewHelpers.authorization_link/2` is used, the assigned `:request_path` will be carried over to the authorization URLs just like in Pow with the create path. The request path will be temporarily stored in the session, and deleted as soon as the user returns for the callback.
=> Add support for request path

CHANGELOG.md, lib/pow_assent/phoenix/views/view_helpers.ex, test/pow_assent/phoenix/views/view_helpers_test.exs
Resolves #111 
This permits link options to be passed on using `PowAssent.Phoenix.ViewHelpers.authorization_link/3`, `PowAssent.Phoenix.ViewHelpers.deauthorization_link/3`, and `PowAssent.Phoenix.ViewHelpers.provider_links/2`.
=> Permit link opts

CHANGELOG.md, lib/pow_assent/operations.ex, lib/pow_assent/phoenix/controllers/registration_controller.ex, lib/pow_assent/plug.ex
=> Use `user_identity_changeset/4` instead of default `changeset/2` in registration controller

CHANGELOG.md, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/phoenix/controllers/registration_controller.ex, lib/pow_assent/plug.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/controllers/registration_controller_test.exs
Resolves #131
Some thoughts before merging this:
- Email verification key should maybe be done in `PowAssent.Plug.callback_upsert/4` also and set as a private key like `pow_assent_callback_email_verified: true`
- Maybe deprecate direct calls to `callback/4` and move to rename methods in `v0.5.0`
- Remove special error cases of `{:bound_to_different_user, changeset}` and `{:invalid_user_id_field, changeset}` and let controller/plug handle it similar to [`Pow.Plug.__prevent_information_leak__ /2`](https://github.com/danschultzer/pow/blob/c404d03e480bbf008cb3c914e812d4cfd8ae65ad/lib/pow/plug.ex#L201-L212)
- Add test cases for `PowAssent.Plug.callback_upsert/4`
=> Refactor callback handling

CHANGELOG.md, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/phoenix/controllers/registration_controller.ex, lib/pow_assent/plug.ex, lib/pow_assent/store/session.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/controllers/registration_controller_test.exs, test/pow_assent/plug_test.exs, test/support/ets_cache_mock.ex
Resolves #134 
`PowAssent.Store.Session` is now used to store the session data instead of `Plug.Session`.
=> Refactor session

CHANGELOG.md, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/phoenix/controllers/registration_controller.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/controllers/registration_controller_test.exs
Supersedes #114
Resolves https://github.com/pow-auth/pow_assent/issues/113#issuecomment-562920929
With #135 it's possible to store a lot more in the session as it's no longer limited by the default `Plug.Session` cookie store. So now we just store the whole changeset in the session and loads it when rendering `:add_user_id` page. The changeset errors will show what's wrong.
=> Store changeset and use when rendering `add_user_id`

.travis.yml, test/pow_assent/config_test.exs, test/support/test_provider.ex
Update travis test with Elixir `1.10.0` and remove missing SSL warnings in test.
=> Test cleanup

CHANGELOG.md, lib/pow_assent/phoenix/controllers/authorization_controller.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs
Resolves #169
The user is redirected to the sign in page with a generic message, and the error is logged.
=> Redirect the user to sign in instead of raising an exception for strategy errors

CHANGELOG.md, lib/pow_assent/config.ex, lib/pow_assent/plug.ex, test/pow_assent/config_test.exs, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/plug_test.exs, test/support/test_provider.ex
Resolves https://github.com/pow-auth/pow_assent/issues/117#issuecomment-571837184
Now the plug in the above issue can be reduced to just this:
```elixir
defmodule MyAppWeb.PowAssent.UpdateProviderConfig do
def init(opts), do: opts
def call(conn, _opts) do
updated_config = [authorization_params: [domain: conn.params["domain"]]]
PowAssent.Plug.merge_provider_config(conn, :auth0, updated_config)
end
end
```
The config will be deep merged. I'm not sure if this is the proper behavior instead of overriding the config values. ~~It should probably also merge with default config in the provider.~~
=> Add helper method to dynamically update provider config

guides/api.md
The redirect_uri function in the example doesn't take a second argument yet a second argument is given in the callback function.
=> Remove second parameter to redirect_uri call in api guide

CHANGELOG.md, lib/pow_assent/plug.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/controllers/registration_controller_test.exs, test/pow_assent/plug_test.exs
This PR resolves an issue where the plug session cookie has a SameSite policy. When using `form_post` method, and setting the plug session cookie with SameSite policy the cookie can't be loaded on POST as the POST comes from another domain. Instead of using plug session, this will not set a separate session cookie for PowAssent auth sessions.
=> Use cookie instead of plug session to prevent SameSite policy issues

CHANGELOG.md, lib/pow_assent/plug.ex, test/pow_assent/plug_test.exs
Pow_assent does its own session handling. In a multi node scenario, if this is not done, the callback could end up in a different node, failing to authenticate.
We could better call out this configuration... or just use the one from Pow. Which probably make sense? not sure, would love to hear what you think or what i am missing here.
=> Extract :cache_store_backend from :pow config

lib/pow_assent/ecto/user_identities/context.ex
See https://github.com/pow-auth/pow_assent/blob/master/lib/pow_assent/ecto/user_identities/context.ex#L88
the function pow_assent_create_user has an arity of 3.
=> Fix arity in docs for pow_assent_create_user/3

lib/pow_assent/plug.ex
This PR updates the `merge_provider_config/3` typespec adding `atom()` as a `provider` typespec. It is breaking on type checks because the provider arg can be a string or atom which is handled [here](https://github.com/pow-auth/pow_assent/blob/master/lib/pow_assent/plug.ex#L433)
=> updating merge_provider_config function typespec

CHANGELOG.md, lib/pow_assent/ecto/user_identities/context.ex
After compiling a project on Elixir 1.12 then I receive this error:
```elixir
warning: module attribute @impl was not set for function create/2 callback (specified in PowAssent.Ecto.UserIdentities.Context). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
lib/pulse/accounts/user_identities.ex:3: Pulse.Accounts.UserIdentities (module)
```
I could not find anything mentioned in the changelog  https://github.com/elixir-lang/elixir/blob/v1.12/CHANGELOG.md, that would indicate that [`defdelegate`](https://hexdocs.pm/elixir/Kernel.html#defdelegate/2) would produce this error when used in https://hexdocs.pm/elixir/typespecs.html#behaviours.
/edit
I think I've found the PR that introduced this: …
=> Fix warning on Elixir 1.12

CHANGELOG.md, lib/pow_assent/plug.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs
According to doc, when registration is disabled :
```
If `:pow_assent_registration` in `conn.private` is set to `false` then
`create_user/4` will not be called and the `:pow_assent_callback_state` set
to `{:error, :create_user}` with `nil` value for
`:pow_assent_callback_error`
```
The callback_upsert function should take this case into account and identify this case as nominal and not as error.
=> Incorrect error flash message when logging in with no allowed registration
