pow-auth/pow_assent

lib/pow_assent/ecto/schema.ex, lib/pow_assent/ecto/user_identities/context.ex, lib/pow_assent/ecto/user_identities/schema.ex, lib/pow_assent/operations.ex, lib/pow_assent/plug.ex, test/pow_assent/ecto/user_identities/context_test.exs
Same as https://github.com/danschultzer/pow/pull/12
=> Use config as last argument

README.md, lib/pow_assent/strategies/azure_oauth2.ex, test/pow_assent/strategies/azure_oauth2.exs
=> Azure OAuth2 strategy

README.md, lib/pow_assent/ecto/schema.ex
Documentation refers to pow_user_identity_changeset function instead of pow_assent_user_identity_changeset
=> Fix docs to pow_assent_user_identity_changeset

lib/pow_assent/ecto/schema.ex
=> Use ecto timestamp generation

lib/pow_assent/strategies/google.ex, test/pow_assent/strategies/google_test.exs
=> Update google strategy urls

lib/pow_assent/strategies/oauth2.ex, test/pow_assent/strategies/oauth2_test.exs
=> Send grant_type with access token request

lib/pow_assent/strategies/facebook.ex, lib/pow_assent/strategies/oauth2.ex, lib/pow_assent/strategies/vk.ex, lib/pow_assent/strategy.ex, test/pow_assent/strategies/facebook_test.exs, test/pow_assent/strategies/vk_test.exs
=> Handle user url query params

CHANGELOG.md, README.md, config/test.exs, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/phoenix/controllers/registration_controller.ex, lib/pow_assent/phoenix/router.ex, lib/pow_assent/plug.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/controllers/registration_controller_test.exs, test/pow_assent/plug_test.exs, test/support/no_registration/phoenix/endpoint.ex, test/support/no_registration/phoenix/router.ex, test/support/user_identities_mock.ex, test/test_helper.exs
=> Move callback session and registration logic to controllers

README.md, lib/pow_assent/ecto/schema.ex, test/pow_assent/ecto/schema_test.exs
=> Update custom changeset docs

README.md, config/test.exs
=> Update readme for custom messages

CHANGELOG.md, lib/pow_assent/strategies/oauth2.ex, test/pow_assent/strategies/facebook_test.exs, test/pow_assent/strategies/oauth2_test.exs, test/pow_assent/strategies/vk_test.exs
=> Put OAuth 2 POST params in body

lib/pow_assent/strategies/twitter.ex
I have fixed the moduledoc for the twitter strategy
=> Fixed typo for strategy

.travis.yml, CHANGELOG.md, guides/CAPTURE_ACCESS_TOKEN.md, lib/pow_assent/ecto/user_identities/context.ex, lib/pow_assent/ecto/user_identities/schema.ex, lib/pow_assent/ecto/user_identities/schema/migration.ex, lib/pow_assent/ecto/user_identities/schema/module.ex, lib/pow_assent/operations.ex, lib/pow_assent/phoenix/controllers/authorization_controller.ex, lib/pow_assent/plug.ex, test/mix/tasks/ecto/pow_assent.ecto.gen.migration_test.exs, test/mix/tasks/ecto/pow_assent.ecto.gen.schema_test.exs, test/pow_assent/ecto/user_identities/context_test.exs, test/pow_assent/ecto/user_identities/schema_test.exs, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/plug_test.exs, test/support/ecto/priv/migrations/4_add_access_refresh_token_to_user_identities.exs, test/support/ecto/user_identities/user_identity.ex, test/support/ecto/user_identities/user_identity_with_access_token.ex, test/support/extensions/email_confirmation/user_identities_mock.ex, test/support/user_identities_mock.ex
Resolves #69 
Replaces all user identity create calls with upsert.
=> Upsert user identity

CHANGELOG.md, mix.exs
This should resolve #71. I'll need to do some testing with elixir 1.9 releases before merging.
=> Include :inets and :ssl in application list

lib/pow_assent/phoenix/messages.ex
Better docs as discussed in #120
=> Update docs on overriding message

guides/legacy_migration.md, mix.exs
=> Add legacy migration guide

lib/pow_assent/ecto/user_identities/context.ex
Making the logic a bit easier to read.
=> Refactor create handling

lib/pow_assent/phoenix/controllers/registration_controller.ex, test/pow_assent/phoenix/controllers/authorization_controller_test.exs, test/pow_assent/phoenix/controllers/registration_controller_test.exs
=> Ensure that session params gets loaded in registration controller

CHANGELOG.md, guides/api.md, mix.exs
=> Add API guide

README.md
Resolves question in #122
To be merged with Pow `v1.0.17` requirement.
=> Note on `pow_prevent_information_leak`

README.md
=> Correct nonce example in readme

lib/pow_assent/phoenix/messages.ex
=> Refactor messages

guides/api.md
=> Update API guide to use newer format in the Pow API guide

README.md
let's make the doc have a nice lock
=> Make all shield use https

README.md, test/pow_assent/plugs/reauthorization_test.exs
=> Add cookie options instructions

CHANGELOG.md, README.md, lib/mix/tasks/ecto/pow_assent.ecto.install.ex, lib/mix/tasks/phoenix/pow_assent.phoenix.install.ex, lib/mix/tasks/pow_assent.install.ex, mix.exs, test/mix/tasks/ecto/pow_assent.ecto.gen.migration_test.exs, test/mix/tasks/ecto/pow_assent.ecto.gen.schema_test.exs, test/mix/tasks/ecto/pow_assent.ecto.install_test.exs, test/mix/tasks/phoenix/pow_assent.phoenix.gen.templates_test.exs, test/mix/tasks/phoenix/pow_assent.phoenix.install_test.exs, test/mix/tasks/pow_assent.install_test.exs, test/support/mix/test_case.ex
Uses the same injection logic as in Pow to configure the app for PowAssent.
=> Add file injections for mix tasks

lib/pow_assent/phoenix/controllers/registration_html.ex
Follow up to https://github.com/pow-auth/pow_assent/issues/240
=> Flip Phoenix 1.7 flags
